/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ounis.biblioteczka;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author AndroidAppsPlatform
 */
public class MainFrame extends javax.swing.JFrame {

    private static final String TITLE = "B i b l i o t e c z k a";
    private static final int SIZE_WIDTH = 1400;
    private static final int SIZE_HEIGHT = 700;
    
    
    private Connection Conn;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(Connection aConn) {
        initComponents();
        Conn = aConn;
        setTitle(TITLE);
        
        btnTabUtils.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    TablesUtil.showTablesUtil(Conn);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTabUtils = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTabUtils.setText("Table Utils");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTabUtils)
                .addContainerGap(675, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTabUtils)
                .addContainerGap(515, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public static void showMainFrame(Connection aConn) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frmMainFrame;
                frmMainFrame = new MainFrame(aConn);
                frmMainFrame.setSize(SIZE_WIDTH, SIZE_HEIGHT);
                frmMainFrame.setResizable(false);
                // poniewa¿ to jest g³ówna forma aplikacji to po jej zamkniêciu
                // nale¿y zamkn¹æ ca³¹ aplikacjê
                frmMainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                
                frmMainFrame.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent event) 
                    {
                        // tutaj jakieœ porz¹dki przy zamkniêciu ramki
                        try
                        {
                            Biblioteczka.getConn().close();
                        }
                        catch (SQLException exception)
                        {
                            System.out.println(String.format("Problem podczas zamykania po³¹czenia: %s", 
                                          Biblioteczka.getConn()) );
                        }
                        finally
                        {
                            System.out.println(
                                  String.format("\nZamykamy pol¹czenie: %s i opuszczamy program: %s ",
                                                          Biblioteczka.getConn(), Biblioteczka.class.getName())); 
                        }    
                    }
                });
                
                Biblioteczka.centerFrame(frmMainFrame);
                frmMainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTabUtils;
    // End of variables declaration//GEN-END:variables
}
